### PR TITLE
chore(atlas-core): added custom fonts download location

### PR DESCRIPTION
**Pull request by gjulivan**
add fonts download location for Mx10 upgrade documents.

original file comes from: https://www.dropbox.com/sh/6dk12xlz4tzh2c5/AADlnBqz6r80Gce5FEjwA3Nra/Icon%20Fonts

### CODE REVIEW

**Comment by iobuhov** [comment]
Can we put this files in `/resources` and demo files to `/examples`?
I don't think this files belong to pacakge

**Review by iobuhov — CHANGES_REQUESTED** [review]
Please move this file to the root of repo

**Comment by iobuhov** [comment]
Also, can we just make a release with zip archive? Then we don't need to put this file under version control.

**Review by iobuhov — APPROVED** [review]
Okay, LGTM

**Review by rahmanunver — APPROVED** [review]

**Review by leonardomendix — APPROVED** [review]

**Pull request merged**
